on: [push, pull_request]
name: CI
jobs:
  build:
    name: "Build on Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix:
        racket-version: ["stable", "current"]
        racket-variant: ["BC", "CS"]
        include:
          - racket-version: current
            experimental: true
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: Bogdanp/setup-racket@v1.9
        with:
          architecture: x64
          distribution: full
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - name: Installing frosthaven-manager and its dependencies
        run: make install RACO_INSTALL_ARGS=--no-docs
      - name: Compiling frosthaven-manager and building its docs
        run: make check-deps RACO_SETUP_ARGS=--unused-pkg-deps
      - name: Install xvfb to run headless tests
        run: apt-get install xvfb
      - name: Testing frosthaven-manager
        run: xvfb-run make test RACO_TEST_ARGS=--no-run-if-absent
