---
name: Deploy documentation to GH Pages
on:
  push:
    branches:
      - main
    paths:
      - 'scribblings/**'
      - '.github/workflows/docs.yml'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.9.1
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: 'stable'
      - name: Install Package
        run: make install RACO_INSTALL_ARGS=--batch
      - name: Build docs
        run: make docs/frosthaven-manager/index.html
      - name: Push to GH Pages
        uses: JamesIves/github-pages-deploy-action@4.4.1
        with:
          folder: docs/frosthaven-manager
          branch: gh-pages
