---
name: Deploy release with compiled applications
on:
  push:
    tags:
      - "v*.*"
      - "v*.*.*"

jobs:
  build_linux:
    name: "Build on Linux Racket CS Stable"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Bogdanp/setup-racket@v1.11
        with:
          architecture: x64
          distribution: full
          variant: CS
          version: stable
      - name: Installing frosthaven-manager and its dependencies
        run: make install RACO_INSTALL_ARGS=--no-docs
      - name: Bundling frosthaven-manager distribution
        run: make linux-FrosthavenManager.tar.gz
      - name: Upload FrosthavenManager artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-dist
          path: linux-FrosthavenManager.tar.gz
  build_macos:
    name: "Build on MacOS Racket CS Stable"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Bogdanp/setup-racket@v1.11
        with:
          architecture: x64
          distribution: full
          variant: CS
          version: stable
      - name: Installing frosthaven-manager and its dependencies
        run: make install RACO_INSTALL_ARGS=--no-docs
      - name: Bundling frosthaven-manager distribution
        run: make macOS-FrosthavenManager.tar.gz
      - name: Upload FrosthavenManager.app artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-dist
          path: macOS-FrosthavenManager.tar.gz
  build_windows:
    name: "Build on Windows Racket CS Stable"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Bogdanp/setup-racket@v1.11
        with:
          architecture: x64
          distribution: full
          variant: CS
          version: stable
      - name: Install make
        run: choco install make -y
      - name: Installing frosthaven-manager and its dependencies
        run: make install RACO_INSTALL_ARGS=--no-docs
      - name: Bundling frosthaven-manager distribution
        run: make windows-FrosthavenManager.zip
      - name: Upload FrosthavenManager artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-dist
          path: windows-FrosthavenManager.zip
  release:
    name: "Release new version"
    runs-on: ubuntu-latest
    needs:
      - build_linux
      - build_macos
      - build_windows
    steps:
      - name: Download FrosthavenManager artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-dist
      - name: Download FrosthavenManager.app artifact
        uses: actions/download-artifact@v4
        with:
          name: macOS-dist
      - name: Download FrosthavenManager.exe artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-dist
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          target_commitish: ${{github.sha}}
          generate_release_notes: true
          files: |
            macOS-FrosthavenManager.tar.gz
            linux-FrosthavenManager.tar.gz
            windows-FrosthavenManager.zip
