---
name: Deploy release with compiled applications
on:
  push:
    tags:
      - "v*.*"
      - "v*.*.*"

jobs:
  build_macos:
    name: "Build on MacOS Racket CS Stable"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Bogdanp/setup-racket@v1.8
        with:
          architecture: x64
          distribution: full
          variant: CS
          version: stable
      - name: Installing frosthaven-manager and its dependencies
        run: raco pkg install --no-docs --auto --name frosthaven-manager
      - name: Creating frosthaven-manager executable
        run: raco exe --gui -o FrosthavenManager manager.rkt
      - name: Creating frosthaven-manager distribution
        run: raco distribute FrosthavenManager FrosthavenManager.app
      - name: Bundling frosthaven-manager distribution
        run: 'tar cvf - FrosthavenManager | gzip >macOS-FrosthavenManager.tar.gz'
      - name: Upload FrosthavenManager.app artifact
        uses: actions/upload-artifact@v3
        with:
          name: macOS-dist
          path: macOS-FrosthavenManager.tar.gz
  release:
    name: "Release new version"
    runs-on: ubuntu-latest
    needs:
      - build_macos
    steps:
      - name: Download FrosthavenManager.app artifact
        uses: actions/download-artifact@v3
        with:
          name: macOS-dist
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          target_commitish: ${{github.sha}}
          generate_release_notes: true
          files: |
            macOS-FrosthavenManager.tar.gz
